import { ArrowLeft, ArrowRight, ClipboardList, Target } from 'lucide-react';

function PreguntaAnalisisNecesidades({ paso, totalPasos, preguntaActual, respuestas, porcentaje, puedeAvanzar, historial, mostrarHistorial, seleccionarRespuesta, avanzar, retroceder, alternarHistorial }) {
  return <div className="w-full max-w-3xl mx-auto animate-fade-in"><div className="relative bg-slate-900 border border-slate-700 rounded-2xl p-6 md:p-8 shadow-xl overflow-hidden"><div className="absolute top-0 left-0 w-full h-1.5 bg-linear-to-r from-cyan-400 via-blue-400 to-indigo-400" /><div className="flex flex-wrap items-center justify-between gap-3 mb-6"><div><h2 className="text-2xl font-bold text-white">Análisis de Necesidades</h2><p className="text-slate-400 mt-1">Responde el cuestionario para sugerir tu enfoque de entrenamiento ideal.</p></div><span className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-cyan-500/40 bg-cyan-500/10 text-cyan-200 text-sm"><ClipboardList size={15} />Paso {paso + 1} de {totalPasos}</span></div>{historial.length > 0 && <div className="mb-6 rounded-lg border border-slate-700 bg-slate-800/40 p-3 flex items-center justify-between gap-3 flex-wrap"><p className="text-sm text-slate-300">Tienes {historial.length} análisis guardado{historial.length === 1 ? '' : 's'}.</p><button onClick={alternarHistorial} className="text-sm font-semibold text-cyan-300 hover:text-cyan-200">{mostrarHistorial ? 'Ocultar historial' : 'Ver historial'}</button></div>}{mostrarHistorial && <HistorialAnalisis historial={historial} compacto />}
    <div className="mb-6"><div className="h-2 rounded-full bg-slate-800 overflow-hidden"><div className="h-full bg-linear-to-r from-cyan-400 to-blue-400 transition-all duration-500" style={{ width: `${porcentaje}%` }} /></div><p className="text-xs text-slate-400 mt-2">Avance: {porcentaje}%</p></div><div className="bg-slate-800/70 border border-slate-700 rounded-xl p-5 md:p-6"><div className="flex items-center gap-2 text-amber-300 mb-2"><Target size={16} /><span className="text-xs uppercase tracking-wider font-semibold">Pregunta activa</span></div><h3 className="text-xl font-bold text-white">{preguntaActual.title}</h3><p className="text-slate-400 mt-1">{preguntaActual.subtitle}</p><div className="grid md:grid-cols-2 gap-3 mt-5">{preguntaActual.options.map(([valor, etiqueta, ayuda]) => { const seleccionada = respuestas[preguntaActual.id] === valor; return <button key={valor} type="button" onClick={() => seleccionarRespuesta(preguntaActual.id, valor)} className={`text-left p-4 rounded-lg border transition-all duration-200 ${seleccionada ? 'border-cyan-400 bg-cyan-500/10 shadow-md shadow-cyan-900/20' : 'border-slate-600 bg-slate-900/70 hover:border-cyan-500/60 hover:bg-slate-900'}`}><p className={`font-semibold ${seleccionada ? 'text-cyan-200' : 'text-slate-100'}`}>{etiqueta}</p><p className="text-sm text-slate-400 mt-1">{ayuda}</p></button>; })}</div></div><div className="mt-6 flex items-center justify-between"><button onClick={retroceder} disabled={paso === 0} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg border border-slate-600 bg-slate-800 text-slate-200 disabled:opacity-40 disabled:cursor-not-allowed hover:bg-slate-700 transition-colors"><ArrowLeft size={16} />Anterior</button><button onClick={avanzar} disabled={!puedeAvanzar} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg border border-cyan-500/50 bg-cyan-500/15 text-cyan-200 font-semibold disabled:opacity-40 disabled:cursor-not-allowed hover:bg-cyan-500/25 transition-colors">{paso === totalPasos - 1 ? 'Analizar respuestas' : 'Siguiente'}<ArrowRight size={16} /></button></div>
  </div></div>;
}

function HistorialAnalisis({ historial, compacto = false }) {
  return <div className={`${compacto ? 'mb-6' : 'mt-6'} border border-slate-700 rounded-xl p-4 bg-slate-950/70`}><h4 className="text-white font-bold mb-3">Historial de análisis</h4><div className="space-y-3 max-h-72 overflow-y-auto pr-1">{historial.map((entrada, indice) => <div key={`${entrada.id}-${indice}`} className="rounded-lg border border-slate-700 bg-slate-900/70 p-3"><p className="text-slate-200 font-semibold">{entrada.recommendation?.title || 'Sin recomendación'}</p><p className="text-sm text-slate-400 mt-1">{entrada.recommendation?.summary || 'Sin resumen disponible.'}</p></div>)}</div></div>;
}

export default PreguntaAnalisisNecesidades;
