const CLASES_CALENDARIO = [
  '[&_.fc_td]:!border-slate-800',
  '[&_.fc_th]:!border-slate-800',
  '[&_.fc_.fc-scrollgrid]:!border-slate-800',
  '[&_.fc_.fc-toolbar]:!mb-3',
  '[&_.fc-daygrid-day-number]:!p-2',
  '[&_.fc-daygrid-day-number]:!text-[0.82rem]',
  '[&_.fc-daygrid-day-number]:!font-black',
  '[&_.fc-daygrid-day-number]:!text-slate-200',
  '[&_.fc-daygrid-day-frame]:min-h-[74px]',
  '[&_.fc-daygrid-day-frame]:transition-all',
  '[&_.fc-daygrid-day:hover_.fc-daygrid-day-frame]:!-translate-y-px',
  '[&_.fc-daygrid-day:hover_.fc-daygrid-day-frame]:!bg-cyan-500/10',
  '[&_.fc-day-sun_.fc-daygrid-day-frame]:!bg-orange-500/[0.06]',
  '[&_.fc-day-past_.fc-daygrid-day-frame]:!bg-slate-500/[0.08]',
  '[&_.fc-day-past:hover_.fc-daygrid-day-frame]:!cursor-not-allowed',
  '[&_.fc-day-past:hover_.fc-daygrid-day-frame]:!bg-red-600/10',
  '[&_.fc_.fc-day-today]:!bg-cyan-600/15',
  '[&_.fc_.fc-day-today]:!shadow-[inset_0_0_0_1px_rgba(34,211,238,0.5)]',
  '[&_.fc_.fc-toolbar-title]:!text-[0.95rem]',
  '[&_.fc_.fc-toolbar-title]:!font-black',
  '[&_.fc_.fc-toolbar-title]:!tracking-[-0.05em]',
  '[&_.fc_.fc-toolbar-title]:!text-white',
  '[&_.fc_.fc-toolbar-title]:!uppercase',
  '[&_.fc-col-header-cell-cushion]:!py-[7px]',
  '[&_.fc-col-header-cell-cushion]:!text-[0.55rem]',
  '[&_.fc-col-header-cell-cushion]:!font-black',
  '[&_.fc-col-header-cell-cushion]:!tracking-[0.1em]',
  '[&_.fc-col-header-cell-cushion]:!text-slate-600',
  '[&_.fc-col-header-cell-cushion]:!uppercase',
  '[&_.fc-event]:!rounded-[7px]',
  '[&_.fc-event]:!border-0',
  '[&_.fc-event]:!bg-linear-to-r',
  '[&_.fc-event]:!from-blue-600',
  '[&_.fc-event]:!to-cyan-500',
  '[&_.fc-event]:!px-1.5',
  '[&_.fc-event]:!py-[3px]',
  '[&_.fc-event]:!text-[0.62rem]',
  '[&_.fc-event]:!font-black',
  '[&_.fc-event]:!shadow-[0_4px_12px_rgba(0,0,0,0.3)]',
].join(' ');

export default function ContenedorCalendario({ children: contenido }) {
  return <div className={CLASES_CALENDARIO}>{contenido}</div>;
}
