export const TEAM_MEMBERS = [
  { name: 'Arturo Santos', role: 'Full Stack Developer', avatar: 'AS', image: 'ArturoSantos.png' },
  { name: 'Leonardo Castillo', role: 'Full Stack Developer', avatar: 'LC', image: 'Leonardo.jpeg' },
  { name: 'Joely Balam', role: 'Full Stack Developer', avatar: 'JB', image: 'JoelyBalam.jpg' },
  { name: 'Agustín Hernández', role: 'Full Stack Developer', avatar: 'AH', image: 'Agustin1.jpeg' },
];

export const TECNOLOGIAS = {
  frontend: {
    title: 'Frontend',
    icon: '💻',
    items: [
      { name: 'JavaScript', description: 'Lenguaje de programación principal del frontend' },
      { name: 'React', description: 'Biblioteca principal para construir interfaces de usuario' },
      { name: 'React Router', description: 'Navegación entre páginas (useNavigate, Routes, Route)' },
      { name: 'Vite', description: 'Build tool y dev server de alta velocidad' },
      { name: 'Tailwind CSS', description: 'Framework de CSS utility-first para diseño responsivo' },
    ],
    conceptsTitle: 'Conceptos y Hooks de React',
    concepts: [
      'Manejo de estado local (useState Hook)',
      'Efectos secundarios y ciclo de vida (useEffect Hook)',
      'Navegación programática (useNavigate Hook)',
      'Componentes funcionales (Functional Components)',
      'Props y composición de componentes (Props & Component Composition)',
      'Manejo de eventos - onClick, onChange, onSubmit (Event Handling)',
      'Formularios controlados (Controlled Forms)',
      'Renderizado condicional (Conditional Rendering)',
      'Renderizado de listas con .map() (List Rendering with .map())',
      'Propiedades clave para listas (Key Props)',
      'Desestructuración de props y estado (Destructuring)',
      'Plantillas literales con backticks (Template Literals)',
      'Funciones flecha (Arrow Functions)',
      'Async/Await para peticiones API (Async/Await)',
      'Importar/Exportar módulos (Import/Export Modules)',
      'Operadores ternarios (Ternary Operators)',
      'Almacenamiento local para persistencia (Local Storage)',
    ],
  },
  backend: {
    title: 'Backend',
    icon: '🛠️',
    items: [
      { name: 'Python', description: 'Lenguaje de programación principal del backend paraprocesamiento de datos.' },
      { name: 'Django', description: 'Framework web de alto nivel para desarrollo rápido y seguro de aplicaciones web.' },
      { name: 'Django REST Framework', description: 'Toolkit para construir APIs RESTful que permiten la comunicación entre frontend y backend.' },
      { name: 'Django CORS Headers', description: 'Permite peticiones desde el frontend React hacia el backend Django (Cross-Origin Resource Sharing).' },
    ],
    conceptsTitle: 'Conceptos de Django',
    concepts: [
      'MVT (Model-View-Template)',
      'ORM de Django',
      'Serializers',
      'ViewSets y APIViews',
      'Autenticación y autorización',
      'Middleware personalizado',
      'Gestión de archivos estáticos',
      'Sistema de migraciones',
    ],
  },
  database: {
    title: 'Base de Datos',
    icon: '💾',
    local: [{ name: 'SQL Server Management Studio 21', description: 'Base de datos local para desarrollo' }],
    cloud: [{ name: 'Render PostgreSQL', description: 'Servicio de base de datos en la nube' }],
    conceptsTitle: 'Conceptos de Base de Datos',
    concepts: ['Modelos relacionales', 'Migraciones automáticas', 'Queries optimizadas', 'Índices y claves foráneas', 'Respaldos y restauración'],
  },
  libraries: {
    title: 'Bibliotecas y Dependencias',
    icon: '📦',
    items: [
      { name: 'Axios', description: 'Cliente HTTP usado para hacer peticiones del frontend React al backend Django (login, registro, membresías).' },
      { name: 'Pillow', description: 'Procesamiento de imágenes de productos, avatares de miembros y fotos de perfil en el sistema.' },
      { name: 'python-decouple', description: 'Manejo seguro de variables de entorno como credenciales de base de datos y claves secretas.' },
      { name: 'whitenoise', description: 'Servir archivos estáticos CSS, JavaScript e imágenes en producción sin necesidad de servidor adicional.' },
      { name: 'gunicorn', description: 'Servidor WSGI de producción para ejecutar la aplicación Django en Render.' },
      { name: 'qrcode', description: 'Generación de códigos QR únicos para cada miembro, usados para check-in/check-out en el gimnasio.' },
    ],
  },
  apis: {
    title: 'APIs y Servicios Externos',
    icon: '🔌',
    items: [
      { name: 'FormSubmit.co', description: 'Servicio de formularios de contacto sin backend' },
      { name: 'Google Maps Embed', description: 'Integración de mapas interactivos' },
      { name: 'Gmail API', description: 'Envío de correos electrónicos transaccionales' },
    ],
  },
  security: {
    title: 'Autenticación y Seguridad',
    icon: '🔐',
    items: [
      { name: 'JWT Tokens', description: 'Generados al hacer login en /admin o /cliente, se envían en cada petición al backend para verificar identidad' },
      { name: 'LocalStorage', description: 'Almacena el token después del login exitoso y se verifica al cargar las páginas protegidas del admin y cliente' },
      { name: 'Protected Routes', description: 'AdminArea y Portal verifican el token antes de mostrar contenido, redirigen a login si no hay autenticación' },
      { name: 'Django Authentication', description: 'Login de adminitrador y cliente login envían credenciales al backend Django que valida usuario/contraseña' },
      { name: 'Password Hashing', description: 'Las contraseñas de administradores y clientes se encriptan automáticamente al registrarse en el sistema' },
      { name: 'CORS Configuration', description: 'Django permite peticiones del frontend React desplegado en Vercel hacia backend en Render' },
      { name: 'Middleware de Autenticación', description: 'cors_middleware.py intercepta todas las peticiones para verificar origen y validar tokens JWT' },
    ],
    conceptsTitle: 'Conceptos de Seguridad Implementados',
    concepts: [
      'Autenticación basada en tokens (Token-based Authentication)',
      'Gestión de sesiones (Session Management)',
      'Control de acceso basado en roles (Role-based Access Control)',
      'Validación de tokens en cada petición (Token Validation)',
      'Redirección automática en rutas protegidas (Protected Route Redirects)',
      'Cierre de sesión y limpieza de tokens (Logout & Token Cleanup)',
      'Separación de permisos: Admin vs Cliente (Permission Separation)',
    ],
  },
  deployment: {
    title: 'Despliegue y DevOps',
    icon: '🚀',
    items: [
      { name: 'Render', description: 'Plataforma de despliegue para backend Django' },
      { name: 'Vercel', description: 'Hosting para frontend React' },
      { name: 'Git & GitHub', description: 'Control de versiones y colaboración' },
      { name: 'Environment Variables', description: 'Configuración segura de credenciales' },
    ],
  },
};
