import { useCallback, useEffect, useState } from 'react';
import { db } from '../../../../firebase/config';
import { collection, getDocs, query, where } from 'firebase/firestore';
import { getCurrentUser as obtenerUsuarioActual, waitForAuthReady as esperarAutenticacion, createTrainerServiceSale as crearVentaServicio, assignTrainerToClient as asignarEntrenador, getClientTrainerAssignment as obtenerAsignacion, getTrainerReviews as obtenerReseñas, addTrainerReview as agregarReseña } from '../../../../firebase';

const ETIQUETAS_SERVICIO = { PERSONAL: 'Personal', GRUPAL: 'Grupal' };
const normalizarTipoServicio = (valor) => { const texto = String(valor || '').trim().toLowerCase(); return texto.includes('grup') ? 'GRUPAL' : texto.includes('personal') || texto.includes('individual') || texto.includes('uno a uno') || texto.includes('1 a 1') ? 'PERSONAL' : ''; };
const formatearMonto = (valor) => Number(valor || 0).toLocaleString();
const obtenerClaveEntrenador = (entrenador = {}) => String(entrenador.authUid || entrenador.uid || entrenador.id || entrenador.email || entrenador.displayName || '').trim().toLowerCase();
const obtenerPrecioServicio = (entrenador = {}) => { const valor = Number(entrenador.trainerServicePrice ?? entrenador.personalServicePrice ?? entrenador.groupServicePrice ?? entrenador.servicePrice ?? entrenador.costoServicio ?? entrenador.costo_servicio ?? entrenador.price ?? 0); return Number.isFinite(valor) && valor > 0 ? valor : 0; };
const obtenerConfiguracionServicio = (entrenador = {}) => { const precioBase = obtenerPrecioServicio(entrenador); const opciones = entrenador.serviceOptions || entrenador.service_options || entrenador.serviceTypes || entrenador.service_types || {}; const precioPersonal = Number(entrenador.personalServicePrice ?? entrenador.personal_service_price ?? opciones.personalPrice ?? opciones.personal_price ?? precioBase); const precioGrupal = Number(entrenador.groupServicePrice ?? entrenador.group_service_price ?? opciones.groupPrice ?? opciones.group_price ?? precioBase); const ofrecePersonal = entrenador.offersPersonalService ?? entrenador.personalServiceEnabled ?? opciones.personal ?? opciones.PERSONAL; const ofreceGrupal = entrenador.offersGroupService ?? entrenador.groupServiceEnabled ?? opciones.group ?? opciones.GRUPAL; return { ofrecePersonal: ofrecePersonal === undefined ? precioBase > 0 : Boolean(ofrecePersonal), ofreceGrupal: ofreceGrupal === undefined ? precioBase > 0 : Boolean(ofreceGrupal), precioPersonal: Number.isFinite(precioPersonal) && precioPersonal > 0 ? precioPersonal : precioBase, precioGrupal: Number.isFinite(precioGrupal) && precioGrupal > 0 ? precioGrupal : precioBase }; };

function usarListaEntrenadores() {
  const [entrenadores, establecerEntrenadores] = useState([]); const [cargando, establecerCargando] = useState(true); const [error, establecerError] = useState(null); const [entrenadorSeleccionado, establecerEntrenadorSeleccionado] = useState(null); const [idCliente, establecerIdCliente] = useState(null); const [idEntrenadorAsignado, establecerIdEntrenadorAsignado] = useState(null); const [asignando, establecerAsignando] = useState(false); const [reseñas, establecerReseñas] = useState({}); const [estrellasSobre, establecerEstrellasSobre] = useState({}); const [entrenadorPendiente, establecerEntrenadorPendiente] = useState(null); const [calificacionPendiente, establecerCalificacionPendiente] = useState(null); const [entrenadorPagoPendiente, establecerEntrenadorPagoPendiente] = useState(null); const [tipoServicioSeleccionado, establecerTipoServicioSeleccionado] = useState('PERSONAL'); const [montoPago, establecerMontoPago] = useState(''); const [metodoPago, establecerMetodoPago] = useState('EFECTIVO'); const [modalExito, establecerModalExito] = useState({ isOpen: false, title: '', message: '' }); const [modalError, establecerModalError] = useState({ isOpen: false, title: '', message: '' });

  useEffect(() => { let desmontado = false; const cargarDatos = async () => { try { establecerCargando(true); await esperarAutenticacion(); const usuario = obtenerUsuarioActual(); if (!usuario) throw new Error('No se pudo identificar al cliente actual'); establecerIdCliente(usuario.uid); const asignacion = await obtenerAsignacion(usuario.uid); if (asignacion.success && !desmontado) establecerIdEntrenadorAsignado(asignacion.data?.trainerId || null); const resultado = await getDocs(query(collection(db, 'users'), where('role', 'in', ['trainer', 'entrenador']))); const unicos = []; const vistos = new Set(); resultado.docs.forEach((documento) => { const entrenador = { id: documento.id, ...documento.data() }; const clave = obtenerClaveEntrenador(entrenador); if (clave && !vistos.has(clave)) { vistos.add(clave); unicos.push(entrenador); } }); if (!desmontado) establecerEntrenadores(unicos); if (unicos.length) { const resultadoReseñas = await obtenerReseñas(unicos.map((entrenador) => entrenador.id)); if (resultadoReseñas.success && !desmontado) establecerReseñas(resultadoReseñas.data); } } catch (errorCarga) { if (!desmontado) establecerError(errorCarga.message || 'No se pudieron cargar los entrenadores'); } finally { if (!desmontado) establecerCargando(false); } }; cargarDatos(); return () => { desmontado = true; }; }, []);

  const obtenerPromedio = useCallback((idEntrenador) => { const lista = reseñas[idEntrenador] || []; return lista.length ? (lista.reduce((total, reseña) => total + reseña.rating, 0) / lista.length).toFixed(1) : null; }, [reseñas]);
  const mostrarError = useCallback((titulo, mensaje) => establecerModalError({ isOpen: true, title: titulo, message: mensaje }), []);
  const seleccionarEntrenador = useCallback((entrenador) => { if (!idCliente) return mostrarError('Sesión no identificada', 'No se pudo identificar al cliente actual.'); if (idEntrenadorAsignado) return mostrarError('Entrenador ya asignado', 'Ya tienes un entrenador asignado. Si deseas cambiar, contacta a recepción.'); establecerEntrenadorPendiente(entrenador); }, [idCliente, idEntrenadorAsignado, mostrarError]);
  const confirmarSeleccion = useCallback(() => { if (!entrenadorPendiente || !idCliente) return; const configuracion = obtenerConfiguracionServicio(entrenadorPendiente); const opciones = []; if (configuracion.ofrecePersonal) opciones.push('PERSONAL'); if (configuracion.ofreceGrupal) opciones.push('GRUPAL'); if (!opciones.length) return mostrarError('Servicios no configurados', 'Este entrenador aún no tiene servicios configurados. Contacta a recepción.'); const tipo = opciones[0]; establecerEntrenadorPendiente(null); establecerEntrenadorPagoPendiente({ ...entrenadorPendiente, opcionesTipoServicio: opciones }); establecerTipoServicioSeleccionado(tipo); establecerMontoPago(String(tipo === 'GRUPAL' ? configuracion.precioGrupal : configuracion.precioPersonal)); establecerMetodoPago('EFECTIVO'); }, [entrenadorPendiente, idCliente, mostrarError]);
  const procesarPago = useCallback(async () => { const entrenador = entrenadorPagoPendiente; const monto = Number(String(montoPago).replace(',', '.')); if (!entrenador || !idCliente) return; if (!Number.isFinite(monto) || monto <= 0) return mostrarError('Monto inválido', 'Ingresa un monto válido mayor a 0 para continuar.'); establecerAsignando(true); try { const venta = await crearVentaServicio({ clientId: idCliente, trainerId: entrenador.id, trainerName: entrenador.displayName || `${entrenador.firstName || ''} ${entrenador.lastName || ''}`.trim() || entrenador.nombre || 'Entrenador', trainerEmail: entrenador.email, amount: monto, paymentMethod: metodoPago, serviceType: tipoServicioSeleccionado }); if (!venta.success) throw new Error(venta.error || 'No se pudo registrar el pago.'); establecerEntrenadorPagoPendiente(null); if (venta.paymentStatus === 'pending') establecerModalExito({ isOpen: true, title: 'Pago pendiente de validación', message: 'Tu pago en efectivo fue registrado. Acude a recepción para validarlo y activar la asignación del entrenador.' }); else { const asignacion = await asignarEntrenador(idCliente, entrenador.id, { serviceType: tipoServicioSeleccionado }); if (!asignacion.success) throw new Error(asignacion.error || 'No se pudo asignar el entrenador.'); establecerIdEntrenadorAsignado(entrenador.id); establecerEntrenadorSeleccionado(entrenador); establecerModalExito({ isOpen: true, title: 'Pago registrado y entrenador asignado', message: `Tu pago fue confirmado y se asignó a ${entrenador.displayName || entrenador.nombre || 'tu entrenador'}.` }); } } catch (errorPago) { mostrarError('Error al procesar pago', errorPago.message || 'Inténtalo de nuevo en unos segundos.'); } finally { establecerAsignando(false); } }, [entrenadorPagoPendiente, idCliente, montoPago, metodoPago, tipoServicioSeleccionado, mostrarError]);
  const calificarEntrenador = useCallback((idEntrenador, calificacion) => { if (!idCliente) return mostrarError('Sesión no identificada', 'No se pudo identificar al cliente actual.'); if (idEntrenadorAsignado !== idEntrenador) return mostrarError('Calificación no permitida', 'Solo puedes calificar a tu entrenador asignado.'); establecerCalificacionPendiente({ idEntrenador, calificacion }); }, [idCliente, idEntrenadorAsignado, mostrarError]);
  const confirmarCalificacion = useCallback(async () => { if (!calificacionPendiente) return; try { const resultado = await agregarReseña(idCliente, calificacionPendiente.idEntrenador, calificacionPendiente.calificacion); if (!resultado.success) throw new Error(resultado.error || 'No se pudo registrar la calificación.'); establecerModalExito({ isOpen: true, title: resultado.updated ? 'Calificación actualizada' : 'Calificación registrada', message: resultado.updated ? 'Tu calificación se actualizó correctamente.' : 'Gracias por calificar a tu entrenador.' }); const actualizadas = await obtenerReseñas(entrenadores.map((entrenador) => entrenador.id)); if (actualizadas.success) establecerReseñas(actualizadas.data); } catch (errorCalificacion) { mostrarError('Error al procesar calificación', errorCalificacion.message || 'Inténtalo de nuevo en unos segundos.'); } finally { establecerCalificacionPendiente(null); } }, [calificacionPendiente, idCliente, entrenadores, mostrarError]);
  const cambiarTipoServicio = (tipo) => { const normalizado = normalizarTipoServicio(tipo) || 'PERSONAL'; establecerTipoServicioSeleccionado(normalizado); if (entrenadorPagoPendiente) { const configuracion = obtenerConfiguracionServicio(entrenadorPagoPendiente); establecerMontoPago(String(normalizado === 'GRUPAL' ? configuracion.precioGrupal : configuracion.precioPersonal)); } };
  const cerrarModalPago = () => { establecerEntrenadorPagoPendiente(null); establecerTipoServicioSeleccionado('PERSONAL'); establecerMontoPago(''); };
  const configuracion = obtenerConfiguracionServicio;
  return { entrenadores, cargando, error, entrenadorSeleccionado, idCliente, idEntrenadorAsignado, entrenadorAsignado: Boolean(idEntrenadorAsignado), asignando, reseñas, estrellasSobre, entrenadorPendiente, calificacionPendiente, entrenadorPagoPendiente, tipoServicioSeleccionado, montoPago, metodoPago, modalExito, modalError, establecerEstrellaSobre: (id, estrella) => establecerEstrellasSobre((anteriores) => ({ ...anteriores, [id]: estrella })), limpiarEstrellaSobre: (id) => establecerEstrellasSobre((anteriores) => ({ ...anteriores, [id]: 0 })), obtenerPromedio, obtenerPrecioPorTipo: (entrenador, tipo) => { const datos = configuracion(entrenador); return normalizarTipoServicio(tipo) === 'GRUPAL' ? datos.precioGrupal : datos.precioPersonal; }, obtenerConfiguracionServicio: configuracion, seleccionarEntrenador, confirmarSeleccion, procesarPago, calificarEntrenador, confirmarCalificacion, cambiarTipoServicio, cerrarModalPago, establecerMontoPago, establecerMetodoPago, cerrarModalSeleccion: () => { if (!asignando) establecerEntrenadorPendiente(null); }, cerrarModalCalificacion: () => establecerCalificacionPendiente(null), cerrarModalExito: () => establecerModalExito({ isOpen: false, title: '', message: '' }), cerrarModalError: () => establecerModalError({ isOpen: false, title: '', message: '' }) };
}

export { ETIQUETAS_SERVICIO, formatearMonto };
export default usarListaEntrenadores;
