export const PREGUNTAS_ANALISIS = [
  { id: 'goal', title: '¿Cuál es tu objetivo principal?', subtitle: 'Esta respuesta tiene el mayor peso en la recomendación.', options: [['lose_fat', 'Perder grasa', 'Bajar porcentaje de grasa corporal.'], ['build_muscle', 'Ganar masa muscular', 'Subir fuerza y volumen muscular.'], ['improve_endurance', 'Mejorar resistencia', 'Rendir mejor en cardio o deporte.'], ['health', 'Mejorar salud general', 'Más energía y bienestar diario.'], ['mobility', 'Movilidad y prevención', 'Evitar molestias y ganar movilidad.']] },
  { id: 'level', title: '¿Cuál es tu nivel actual?', subtitle: 'Para ajustar la intensidad inicial.', options: [['beginner', 'Principiante', 'Menos de 6 meses entrenando.'], ['intermediate', 'Intermedio', 'Entre 6 meses y 2 años.'], ['advanced', 'Avanzado', 'Más de 2 años entrenando.']] },
  { id: 'days', title: '¿Cuántos días por semana puedes entrenar?', subtitle: 'Así definimos frecuencia y volumen.', options: [['2_3', '2 a 3 días', 'Agenda limitada.'], ['4_5', '4 a 5 días', 'Agenda balanceada.'], ['6_plus', '6 o más días', 'Alta disponibilidad.']] },
  { id: 'session_length', title: '¿Cuánto dura tu sesión ideal?', subtitle: 'Para elegir formato de rutina.', options: [['30_45', '30 a 45 minutos', 'Entrenamientos compactos.'], ['45_60', '45 a 60 minutos', 'Formato estándar.'], ['60_plus', 'Más de 60 minutos', 'Mayor volumen por sesión.']] },
  { id: 'preference', title: '¿Qué tipo de trabajo disfrutas más?', subtitle: 'La adherencia mejora cuando te gusta el método.', options: [['weights', 'Pesas', 'Trabajo de fuerza e hipertrofia.'], ['cardio', 'Cardio', 'Resistencia y acondicionamiento.'], ['mixed', 'Mixto', 'Combinación de fuerza y cardio.'], ['functional', 'Funcional/movilidad', 'Movimiento integral y estabilidad.']] },
  { id: 'limitation', title: '¿Tienes alguna limitación actual?', subtitle: 'Nos ayuda a priorizar seguridad.', options: [['none', 'Ninguna', 'Sin molestias relevantes.'], ['joint_pain', 'Molestias articulares', 'Dolor recurrente leve/moderado.'], ['injury_history', 'Historial de lesión', 'Lesión previa que cuidar.'], ['high_stress', 'Estrés/fatiga alta', 'Recuperación limitada esta etapa.']] },
];

const PLANES = { hypertrophy_strength: ['Fuerza e Hipertrofia', 'Ideal para desarrollar masa muscular, subir fuerza y mejorar composición corporal.', 'Movimientos compuestos, progresión de cargas y técnica.', '4-5 sesiones por semana', '45-70 minutos por sesión'], fat_loss_metabolic: ['Pérdida de Grasa Metabólica', 'Prioriza gasto energético, mantenimiento muscular y consistencia semanal.', 'Circuitos de fuerza + cardio estratégico + trabajo por intervalos.', '4-6 sesiones por semana', '35-60 minutos por sesión'], endurance_conditioning: ['Resistencia y Acondicionamiento', 'Pensado para elevar tu capacidad cardiovascular y rendimiento deportivo.', 'Bloques aeróbicos, intervalos y control de zonas de esfuerzo.', '4-5 sesiones por semana', '40-70 minutos por sesión'], functional_mobility: ['Funcional y Movilidad', 'Enfocado en salud articular, estabilidad y patrones de movimiento seguros.', 'Control motor, movilidad activa y fuerza funcional.', '3-5 sesiones por semana', '30-55 minutos por sesión'] };
const REGLAS = { goal: { lose_fat: { fat_loss_metabolic: 5, endurance_conditioning: 2 }, build_muscle: { hypertrophy_strength: 5 }, improve_endurance: { endurance_conditioning: 5, fat_loss_metabolic: 1 }, health: { functional_mobility: 3, fat_loss_metabolic: 2 }, mobility: { functional_mobility: 5 } }, level: { beginner: { functional_mobility: 2, fat_loss_metabolic: 1 }, intermediate: { hypertrophy_strength: 1, endurance_conditioning: 1, fat_loss_metabolic: 1 }, advanced: { hypertrophy_strength: 2, endurance_conditioning: 2 } }, days: { '2_3': { functional_mobility: 2, hypertrophy_strength: 1 }, '4_5': { hypertrophy_strength: 2, endurance_conditioning: 2, fat_loss_metabolic: 2 }, '6_plus': { fat_loss_metabolic: 2, endurance_conditioning: 3 } }, session_length: { '30_45': { fat_loss_metabolic: 2, functional_mobility: 1 }, '45_60': { hypertrophy_strength: 2, endurance_conditioning: 2 }, '60_plus': { hypertrophy_strength: 2, endurance_conditioning: 2 } }, preference: { weights: { hypertrophy_strength: 3 }, cardio: { endurance_conditioning: 3, fat_loss_metabolic: 2 }, mixed: { fat_loss_metabolic: 2, hypertrophy_strength: 1, endurance_conditioning: 1 }, functional: { functional_mobility: 3 } }, limitation: { none: { hypertrophy_strength: 1, endurance_conditioning: 1 }, joint_pain: { functional_mobility: 3 }, injury_history: { functional_mobility: 4 }, high_stress: { functional_mobility: 2, fat_loss_metabolic: 1 } } };

export const construirRecomendacion = (respuestas) => { const puntajes = Object.fromEntries(Object.keys(PLANES).map((clave) => [clave, 0])); Object.entries(respuestas).forEach(([pregunta, opcion]) => Object.entries(REGLAS[pregunta]?.[opcion] || {}).forEach(([plan, puntos]) => { puntajes[plan] += puntos; })); const claveGanadora = Object.keys(PLANES).reduce((mejor, actual) => puntajes[actual] > puntajes[mejor] ? actual : mejor, 'hypertrophy_strength'); const [title, summary, focus, weekly, session] = PLANES[claveGanadora]; return { key: claveGanadora, title, summary, focus, weekly, session, score: puntajes }; };
export const obtenerClaveAnalisis = () => { try { const usuario = JSON.parse(localStorage.getItem('firebaseUser') || 'null'); return usuario?.uid || usuario?.user?.uid ? `training-needs-analysis-${usuario.uid || usuario.user.uid}` : 'training-needs-analysis-anon'; } catch { return 'training-needs-analysis-anon'; } };
export const leerHistorialAnalisis = (valor) => { try { const datos = JSON.parse(valor || '[]'); if (Array.isArray(datos)) return datos; return datos?.recommendation && datos?.answers ? [{ id: datos.id || Date.now(), completedAt: datos.completedAt || new Date().toISOString(), answers: datos.answers, recommendation: datos.recommendation }] : []; } catch { return []; } };
export const formatearFechaAnalisis = (valor) => { const fecha = new Date(valor); return valor && !Number.isNaN(fecha.getTime()) ? fecha.toLocaleString('es-MX', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : 'Sin fecha'; };
