import { useCallback, useEffect, useState } from 'react';
import { db } from '../firebase/config';
import { collection, getDocs } from 'firebase/firestore';
import { addNutritionistReview as agregarReseña, assignNutritionistToClient as asignarNutriologo, getClientNutritionistAssignment as obtenerAsignacion, getCurrentUser as obtenerUsuarioActual, getNutritionistReviews as obtenerReseñas, waitForAuthReady as esperarAutenticacion } from '../firebase';

const esNutriologoActivo = (usuario = {}) => { const rol = String(usuario.role || usuario.user_type || '').toLowerCase(); const estado = String(usuario.nutritionistStatus || usuario.contractStatus || '').toLowerCase(); return usuario.isActive !== false && estado !== 'inactive' && ['nutritionist', 'nutriologo', 'nutriologa', 'nutriologo/a', 'nutricionista', 'nutri'].includes(rol); };

function usarListaNutriologos() {
  const [nutriologos, establecerNutriologos] = useState([]); const [cargando, establecerCargando] = useState(true); const [error, establecerError] = useState(null); const [nutriologoSeleccionado, establecerNutriologoSeleccionado] = useState(null); const [idCliente, establecerIdCliente] = useState(null); const [idNutriologoAsignado, establecerIdNutriologoAsignado] = useState(null); const [asignando, establecerAsignando] = useState(false); const [reseñas, establecerReseñas] = useState({}); const [estrellasSobre, establecerEstrellasSobre] = useState({}); const [nutriologoPendiente, establecerNutriologoPendiente] = useState(null); const [mostrarSeleccion, establecerMostrarSeleccion] = useState(false); const [calificacionPendiente, establecerCalificacionPendiente] = useState(null); const [mostrarCalificacion, establecerMostrarCalificacion] = useState(false); const [enviandoCalificacion, establecerEnviandoCalificacion] = useState(false); const [modalExito, establecerModalExito] = useState({ isOpen: false, title: '', message: '', subMessage: '' });
  useEffect(() => { let desmontado = false; const cargar = async () => { try { await esperarAutenticacion(); const usuario = obtenerUsuarioActual(); if (!usuario) throw new Error('No se pudo identificar al cliente actual'); establecerIdCliente(usuario.uid); const asignacion = await obtenerAsignacion(usuario.uid); if (asignacion.success && !desmontado) establecerIdNutriologoAsignado(asignacion.data?.nutritionistId || null); const resultado = await getDocs(collection(db, 'users')); const lista = resultado.docs.map((documento) => ({ id: documento.id, ...documento.data() })).filter(esNutriologoActivo); if (!desmontado) establecerNutriologos(lista); if (lista.length) { const reseñas = await obtenerReseñas(lista.map((nutriologo) => nutriologo.id)); if (reseñas.success && !desmontado) establecerReseñas(reseñas.data); } } catch (errorCarga) { if (!desmontado) establecerError(errorCarga.message || 'No se pudieron cargar los nutriólogos'); } finally { if (!desmontado) establecerCargando(false); } }; cargar(); return () => { desmontado = true; }; }, []);
  const obtenerPromedio = useCallback((id) => { const lista = reseñas[id] || []; return lista.length ? (lista.reduce((total, reseña) => total + reseña.rating, 0) / lista.length).toFixed(1) : null; }, [reseñas]);
  const calificarNutriologo = (id, calificacion) => { if (!idCliente) return window.alert('Error: No se pudo identificar al cliente'); if (idNutriologoAsignado !== id) return window.alert('Solo puedes calificar a tu nutriólogo asignado'); establecerCalificacionPendiente({ idNutriologo: id, calificacion }); establecerMostrarCalificacion(true); };
  const confirmarCalificacion = async () => { if (!calificacionPendiente) return; establecerEnviandoCalificacion(true); try { const resultado = await agregarReseña(idCliente, calificacionPendiente.idNutriologo, calificacionPendiente.calificacion); if (!resultado.success) throw new Error(resultado.error || 'No se pudo registrar la calificación.'); establecerModalExito({ isOpen: true, title: resultado.updated ? 'Calificación actualizada' : 'Calificación registrada', message: resultado.updated ? 'Tu calificación se actualizó correctamente.' : '¡Gracias por calificar a tu nutriólogo!', subMessage: '' }); const actualizadas = await obtenerReseñas(nutriologos.map((nutriologo) => nutriologo.id)); if (actualizadas.success) establecerReseñas(actualizadas.data); } catch { window.alert('Error al procesar la calificación. Inténtalo de nuevo.'); } finally { establecerEnviandoCalificacion(false); establecerMostrarCalificacion(false); establecerCalificacionPendiente(null); } };
  const seleccionarNutriologo = (nutriologo) => { if (!idCliente) return window.alert('Error: No se pudo identificar al cliente'); if (idNutriologoAsignado) return window.alert('Ya tienes un nutriólogo asignado. Si deseas cambiar, contacta a recepción.'); establecerNutriologoPendiente(nutriologo); establecerMostrarSeleccion(true); };
  const confirmarSeleccion = async () => { if (!nutriologoPendiente) return; establecerAsignando(true); try { const resultado = await asignarNutriologo(idCliente, nutriologoPendiente.id); if (!resultado.success) throw new Error(resultado.error || 'No se pudo asignar el nutriólogo.'); establecerIdNutriologoAsignado(nutriologoPendiente.id); establecerNutriologoSeleccionado(nutriologoPendiente); establecerModalExito({ isOpen: true, title: 'Contratación exitosa', message: `¡Felicidades! Has contratado a ${nutriologoPendiente.displayName || nutriologoPendiente.nombre || 'tu nutriólogo'} como tu nutriólogo.`, subMessage: 'Pronto recibirás tu plan nutricional personalizado.' }); } catch { window.alert('Error al procesar la selección. Inténtalo de nuevo.'); } finally { establecerAsignando(false); establecerMostrarSeleccion(false); establecerNutriologoPendiente(null); } };
  return { nutriologos, cargando, error, nutriologoSeleccionado, idCliente, idNutriologoAsignado, asignando, reseñas, estrellasSobre, nutriologoPendiente, mostrarSeleccion, calificacionPendiente, mostrarCalificacion, enviandoCalificacion, modalExito, obtenerPromedio, seleccionarNutriologo, confirmarSeleccion, calificarNutriologo, confirmarCalificacion, establecerEstrellaSobre: (id, estrella) => establecerEstrellasSobre((anteriores) => ({ ...anteriores, [id]: estrella })), limpiarEstrellaSobre: (id) => establecerEstrellasSobre((anteriores) => ({ ...anteriores, [id]: 0 })), cerrarSeleccion: () => { if (!asignando) { establecerMostrarSeleccion(false); establecerNutriologoPendiente(null); } }, cerrarCalificacion: () => { if (!enviandoCalificacion) { establecerMostrarCalificacion(false); establecerCalificacionPendiente(null); } }, cerrarExito: () => establecerModalExito({ isOpen: false, title: '', message: '', subMessage: '' }) };
}

export default usarListaNutriologos;
