import { Activity, CalendarDays, Dumbbell, FileText, Layers, Zap, User } from 'lucide-react';
import { formatearFechaHora } from '../utilidadesRutinaCliente';

function InsigniaEstadistica({ icono: Icono, etiqueta, valor, color }) {
  const colores = { blue: 'bg-blue-500/15 border-blue-500/30 text-blue-300', violet: 'bg-violet-500/15 border-violet-500/30 text-violet-300', emerald: 'bg-emerald-500/15 border-emerald-500/30 text-emerald-300', amber: 'bg-amber-500/15 border-amber-500/30 text-amber-300' };
  return <div className={`inline-flex flex-col items-center gap-1 rounded-xl border px-4 py-2 min-w-20 ${colores[color] || colores.blue}`}><Icono size={14} /><span className="font-bold text-base leading-none">{valor || '—'}</span><span className="text-[10px] uppercase tracking-wide opacity-70">{etiqueta}</span></div>;
}

function EncabezadoRutinaCliente({ rutina, nombreMiembro, estadisticas, tieneArchivos }) {
  return <div className="relative overflow-hidden rounded-2xl border border-slate-700 bg-linear-to-br from-slate-900 via-slate-900 to-blue-950 p-5 md:p-7"><div className="absolute inset-0 pointer-events-none"><div className="absolute -top-8 -right-8 w-40 h-40 rounded-full bg-blue-600/10 blur-2xl" /><div className="absolute -bottom-6 -left-6 w-32 h-32 rounded-full bg-violet-600/10 blur-2xl" /></div><div className="relative flex flex-col sm:flex-row sm:items-start justify-between gap-4"><div className="space-y-1"><div className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-blue-400 mb-2"><Activity size={13} />Plan de entrenamiento</div><h2 className="text-2xl md:text-3xl font-extrabold text-white leading-tight">{rutina.routineName || 'Mi Rutina'}</h2><p className="text-slate-400 text-sm flex items-center gap-1.5 mt-1"><User size={13} />{nombreMiembro}</p></div><div className="shrink-0 text-right space-y-1"><p className="text-xs text-slate-500 flex items-center gap-1 justify-end"><CalendarDays size={12} />Actualizado</p><p className="text-xs text-slate-300 font-medium">{formatearFechaHora(rutina.updatedAt || rutina.createdAt)}</p>{rutina.trainerEmail && <p className="text-xs text-slate-500 flex items-center gap-1 justify-end mt-1"><Dumbbell size={12} />{rutina.trainerEmail}</p>}</div></div><div className="relative mt-5 flex flex-wrap gap-3"><InsigniaEstadistica icono={Dumbbell} etiqueta="Ejercicios" valor={estadisticas.ejercicios} color="blue" />{estadisticas.dias > 0 && <InsigniaEstadistica icono={CalendarDays} etiqueta="Días" valor={estadisticas.dias} color="violet" />}{estadisticas.dias === 0 && estadisticas.totalSeries > 0 && <InsigniaEstadistica icono={Layers} etiqueta="Series tot." valor={estadisticas.totalSeries} color="violet" />}{tieneArchivos && <InsigniaEstadistica icono={FileText} etiqueta="Archivos" valor={rutina.files.length} color="amber" />}<InsigniaEstadistica icono={Zap} etiqueta="Estado" valor="Activa" color="emerald" /></div></div>;
}

export default EncabezadoRutinaCliente;
