import ModalConfirmacion from '../../../modales/ModalConfirmacion';
import ModalExito from '../../../modales/ModalExito';
import ErrorModal from '../../../modales/ErrorModal';
import ModalPagoServicioEntrenador from '../../../modales/ModalPagoServicioEntrenador';
import { ETIQUETAS_SERVICIO } from '../hooks/usarListaEntrenadores';

function ModalesEntrenadoresCliente(estado) {
  const nombrePendiente = estado.entrenadorPendiente?.displayName || estado.entrenadorPendiente?.nombre || 'este entrenador';
  return <><ModalConfirmacion isOpen={Boolean(estado.entrenadorPendiente)} onClose={estado.cerrarModalSeleccion} onConfirm={estado.confirmarSeleccion} title="Confirmar entrenador" message={estado.entrenadorPendiente ? `¿Estas seguro de seleccionar a ${nombrePendiente} como tu entrenador?\n\nEsto iniciara tu plan de entrenamiento personalizado.` : ''} confirmLabel={estado.asignando ? 'Asignando...' : 'Si, Seleccionar'} variant="info" /><ModalPagoServicioEntrenador isOpen={Boolean(estado.entrenadorPagoPendiente)} title="Confirmar pago del servicio" subtitle="Para continuar con tu servicio de entrenamiento, elige el tipo de servicio y confirma el pago." serviceType={estado.tipoServicioSeleccionado} serviceTypeOptions={(estado.entrenadorPagoPendiente?.opcionesTipoServicio || []).map((tipo) => ({ value: tipo, label: ETIQUETAS_SERVICIO[tipo] || tipo }))} serviceTypeReadOnly={(estado.entrenadorPagoPendiente?.opcionesTipoServicio || []).length <= 1} onServiceTypeChange={estado.cambiarTipoServicio} value={estado.montoPago} amountReadOnly amountHelperText="El monto se ajusta automáticamente según el tipo de servicio seleccionado." paymentMethod={estado.metodoPago} onChange={estado.establecerMontoPago} onPaymentMethodChange={estado.establecerMetodoPago} onConfirm={estado.procesarPago} confirmLabel={estado.asignando ? 'Procesando...' : 'Pagar y asignar'} onClose={estado.cerrarModalPago} /><ModalConfirmacion isOpen={Boolean(estado.calificacionPendiente)} onClose={estado.cerrarModalCalificacion} onConfirm={estado.confirmarCalificacion} title="Confirmar calificación" message={estado.calificacionPendiente ? `¿Calificar a este entrenador con ${estado.calificacionPendiente.calificacion} estrella(s)?` : ''} confirmLabel="Sí, Calificar" variant="info" /><ModalExito isOpen={estado.modalExito.isOpen} onClose={estado.cerrarModalExito} title={estado.modalExito.title} message={estado.modalExito.message} /><ErrorModal isOpen={estado.modalError.isOpen} onClose={estado.cerrarModalError} title={estado.modalError.title} message={estado.modalError.message} /></>;
}

export default ModalesEntrenadoresCliente;
