import { ArrowLeft, CheckCircle2, ClipboardList, Sparkles } from 'lucide-react';
import { formatearFechaAnalisis } from '../hooks/datosAnalisisNecesidades';

function ResultadoAnalisisNecesidades({ recomendacion, reiniciar, historial, mostrarHistorial, alternarHistorial }) {
  return <div className="w-full max-w-3xl mx-auto animate-fade-in"><div className="relative bg-slate-900 border border-slate-700 rounded-2xl p-6 md:p-8 shadow-xl overflow-hidden"><div className="absolute top-0 left-0 w-full h-1.5 bg-linear-to-r from-amber-400 via-orange-400 to-rose-400" /><div className="flex items-center gap-3 mb-4"><div className="p-2.5 rounded-xl bg-emerald-500/10 text-emerald-400"><CheckCircle2 size={22} /></div><h2 className="text-2xl md:text-3xl font-bold text-white">Tipo de entrenamiento sugerido</h2></div><div className="bg-slate-800/70 border border-slate-700 rounded-xl p-5 md:p-6"><div className="flex items-start justify-between gap-4 flex-wrap"><div><p className="text-sm text-slate-400 mb-1">Recomendación principal</p><h3 className="text-xl md:text-2xl font-extrabold text-amber-300">{recomendacion.title}</h3></div><span className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-amber-500/10 text-amber-300 text-sm border border-amber-500/30"><Sparkles size={15} />Sugerencia automática</span></div><p className="text-slate-200 mt-4 leading-relaxed">{recomendacion.summary}</p><div className="grid md:grid-cols-2 gap-3 mt-5">{[['Enfoque', recomendacion.focus], ['Frecuencia sugerida', recomendacion.weekly], ['Duración sugerida', recomendacion.session]].map(([etiqueta, valor]) => <div key={etiqueta} className="bg-slate-900/70 border border-slate-700 rounded-lg p-3 md:col-span-1"><p className="text-xs uppercase tracking-wider text-slate-400">{etiqueta}</p><p className="text-slate-200 mt-1">{valor}</p></div>)}</div></div><div className="mt-6 flex flex-wrap gap-3"><button onClick={reiniciar} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg bg-slate-800 hover:bg-slate-700 border border-slate-600 text-white font-semibold transition-colors"><ArrowLeft size={16} />Volver a responder</button>{historial.length > 0 && <button onClick={alternarHistorial} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg bg-slate-800 hover:bg-slate-700 border border-slate-600 text-white font-semibold transition-colors"><ClipboardList size={16} />{mostrarHistorial ? 'Ocultar historial' : `Ver historial (${historial.length})`}</button>}<p className="text-sm text-slate-400 self-center">Esta recomendación es inicial. Tu entrenador puede ajustarla según evaluación técnica.</p></div>{mostrarHistorial && <HistorialAnalisis historial={historial} />}</div></div>;
}

function HistorialAnalisis({ historial }) { return <div className="mt-6 border border-slate-700 rounded-xl p-4 bg-slate-950/70"><h4 className="text-white font-bold mb-3">Historial de análisis</h4><div className="space-y-3 max-h-72 overflow-y-auto pr-1">{historial.map((entrada, indice) => <div key={`${entrada.id}-${indice}`} className="rounded-lg border border-slate-700 bg-slate-900/70 p-3"><div className="flex items-center justify-between gap-3 flex-wrap"><p className="text-slate-200 font-semibold">{entrada.recommendation?.title || 'Sin recomendación'}</p><p className="text-xs text-slate-400">{formatearFechaAnalisis(entrada.completedAt)}</p></div><p className="text-sm text-slate-400 mt-1">{entrada.recommendation?.summary || 'Sin resumen disponible.'}</p></div>)}</div></div>; }

export default ResultadoAnalisisNecesidades;
